//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTION__MIFA
{
    using System;
    using System.Collections.Generic;
    
    public partial class produit
    {
        public int idproduit { get; set; }
        public string nomp { get; set; }
        public double prix { get; set; }
        public int idcategorie { get; set; }
        public int quantite { get; set; }
    
        public virtual categorie categorie { get; set; }
    }
}
